version: "2.3"

services:
    chess_game-container:
        image: ghcr.io/userver-framework/docker-userver-build-base:v1a
        privileged: true
        network_mode: bridge
        environment:
          - PREFIX=${PREFIX:-~/.local}
          - CC
          - CCACHE_DIR=/chess_game/.ccache
          - CCACHE_HASHDIR
          - CCACHE_NOHASHDIR
          - CCACHE_PREFIX
          - CCACHE_SIZE
          - CMAKE_OPTS
          - CORES_DIR=/cores
          - CXX
          - MAKE_OPTS
        volumes:
          - .:/chess_game:rw
          - ./third_party/userver/tools/docker:/tools:ro
        ports:
          - 8080:8080
        working_dir: /chess_game
        entrypoint:
          - /tools/run_as_user.sh
        depends_on:
          - redis-sentinel
        networks:
          - redis
    redis-sentinel:
        container_name: service-redis-sentinel
        image: redis:7.0
        command: redis-server /data/sentinel.conf --sentinel
        ports:
          - "26379:26379"
        volumes:
          - ./sentinel.conf:/data/sentinel.conf:rw
        networks:
          - redis
        depends_on:
          - redis
    redis:
      image: redis:7.0
      command: redis-server --cluster-enabled
      ports:
        - "6379:6379"
      networks:
        - redis
networks:
  redis:
